swagger: '2.0'
info:
  title: PronosticApp API
  description: Es la hora de los pronósticos.
  version: 1.0.0
host: localhost
schemes:
  - http
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: "Jugadores"
    description: "Everything about your Pets"
  - name: "Comunidades"
    description: "Access to Petstore orders"
  - name: "Históricos"
paths:
  /player/register:
    post:
      summary: Crear un nuevo jugador
      description: |
        Crear un jugador.
      parameters:
        - name: body
          in: body
          description: Datos del jugador.
          required: true
          schema:
            $ref: "#/definitions/Jugador"
      tags:
        - jugador
      responses:
        '200':
          description: An array of products
          schema:
            $ref: '#/definitions/MessageResult'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/MessageResult'
  /player/login:
    post:
      summary: Login de un jugador
      description: |
        Login de un jugador.
      parameters:
        - name: body
          in: body
          description: Datos del jugador.
          required: true
          schema:
            $ref: "#/definitions/Jugador"
      tags:
        - jugador
      responses:
        '200':
          description: Datos del jugador
          schema:
            $ref: '#/definitions/Jugador'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/MessageResult'
      security:
        - token: []
securityDefinitions:
  token:
    type: "apiKey"
    name: "X-Auth-Token"
    in: "header"
definitions:
  Jugador:
    type: object
    required:
      - nickname
      - email
      - password
    properties:
      id:
        type: string
        description: >-
          Unique identifier representing a specific product for a given latitude
          & longitude. For example, uberX in San Francisco will have a different
          product_id than uberX in Los Angeles.
      nickname:
        type: string
        description: Description of product.
      email:
        type: string
        description: Display name of product.
      password:
        type: string
        description: Display name of product.
      nombre:
        type: string
        description: 'Capacity of product. For example, 4 people.'
      apellidos:
        type: string
        description: Image URL representing the product.
  MessageResult:
    type: object
    properties:
      error:
        type: boolean
      descripcion:
        type: string
      mensajes:
        type: array
        items:
          type: string
