swagger: '2.0'
info:
  title: PronosticApp API
  description: Es la hora de los pronósticos.
  version: 1.0.0
host: {{{server}}}
schemes:
  - http
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /player/create:
    post:
      summary: Crear un nuevo jugador
      description: |
        Crear un jugador.
      parameters:
        - name: player
          in: body
          description: Datos del jugador.
          required: true
          schema:
            type: object
            required:
              - nickname
              - email
              - password
            properties:
              nickname:
                type: string
              email:
                type: string
              password:
                type: string
              nombre:
                type: string
              apellidos:
                type: string
      tags:
        - Products
      responses:
        '200':
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Product:
    type: object
    properties:
      product_id:
        type: string
        description: >-
          Unique identifier representing a specific product for a given latitude
          & longitude. For example, uberX in San Francisco will have a different
          product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: 'Capacity of product. For example, 4 people.'
      image:
        type: string
        description: Image URL representing the product.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string